export interface BookData {
  title: string;
  author: string;
  season: string;
  chapter: number;
  theme: string;
  quote: string;
}

export const BOOKS: BookData[] = [
  // Season 1: The Village (Chapters 1-5)
  { title: 'Deep Work', author: 'Cal Newport', season: 'The Village', chapter: 1, theme: 'Focus', quote: 'The ability to perform deep work is becoming increasingly rare\u2014and increasingly valuable.' },
  { title: 'Sapiens', author: 'Yuval Noah Harari', season: 'The Village', chapter: 1, theme: 'Humanity', quote: 'You could never convince a monkey to give you a banana by promising him limitless bananas after death.' },
  { title: 'Educated', author: 'Tara Westover', season: 'The Village', chapter: 1, theme: 'Identity', quote: 'You can love someone and still choose to say goodbye to them.' },
  { title: 'The Alchemist', author: 'Paulo Coelho', season: 'The Village', chapter: 1, theme: 'Destiny', quote: 'When you want something, all the universe conspires in helping you to achieve it.' },
  { title: 'Man\u2019s Search for Meaning', author: 'Viktor Frankl', season: 'The Village', chapter: 1, theme: 'Purpose', quote: 'He who has a why to live for can bear almost any how.' },
  { title: 'Think Like a Monk', author: 'Jay Shetty', season: 'The Village', chapter: 2, theme: 'Stillness', quote: 'We can\u2019t be happy all the time, but we can live with purpose.' },
  { title: 'Blink', author: 'Malcolm Gladwell', season: 'The Village', chapter: 2, theme: 'Intuition', quote: 'Truly successful decision making relies on a balance between deliberate and instinctive thinking.' },
  { title: 'The Laws of Human Nature', author: 'Robert Greene', season: 'The Village', chapter: 2, theme: 'Psychology', quote: 'Your mind is your most precious possession. Defend it.' },
  { title: 'All Marketers Are Liars', author: 'Seth Godin', season: 'The Village', chapter: 2, theme: 'Story', quote: 'People do not buy goods and services. They buy relations, stories and magic.' },
  { title: 'The Power of Now', author: 'Eckhart Tolle', season: 'The Village', chapter: 2, theme: 'Presence', quote: 'Realize deeply that the present moment is all you ever have.' },
  { title: 'Why We Sleep', author: 'Matthew Walker', season: 'The Village', chapter: 3, theme: 'Body', quote: 'Sleep is the single most effective thing we can do to reset our brain and body health each day.' },
  { title: 'The 5 AM Club', author: 'Robin Sharma', season: 'The Village', chapter: 3, theme: 'Discipline', quote: 'Own your morning. Elevate your life.' },
  { title: 'Atomic Habits', author: 'James Clear', season: 'The Village', chapter: 3, theme: 'Habits', quote: 'You do not rise to the level of your goals. You fall to the level of your systems.' },
  { title: 'Can\u2019t Hurt Me', author: 'David Goggins', season: 'The Village', chapter: 3, theme: 'Resilience', quote: 'The most important conversations you\u2019ll ever have are the ones you\u2019ll have with yourself.' },
  { title: 'High Performance Habits', author: 'Brendon Burchard', season: 'The Village', chapter: 3, theme: 'Performance', quote: 'How you show up each day defines who you become.' },
  { title: 'The Richest Man in Babylon', author: 'George S. Clason', season: 'The Village', chapter: 4, theme: 'Finance', quote: 'A part of all you earn is yours to keep.' },
  { title: 'Built to Serve', author: 'Dan J. Sanders', season: 'The Village', chapter: 4, theme: 'Service', quote: 'Purpose is the quiet engine beneath everything that lasts.' },
  { title: 'Siddhartha', author: 'Hermann Hesse', season: 'The Village', chapter: 4, theme: 'Seeking', quote: 'Wisdom cannot be imparted. Wisdom that a wise man attempts to impart always sounds like foolishness.' },
  { title: 'On the Shortness of Life', author: 'Seneca', season: 'The Village', chapter: 4, theme: 'Time', quote: 'It is not that we have a short time to live, but that we waste a lot of it.' },
  { title: 'Shoe Dog', author: 'Phil Knight', season: 'The Village', chapter: 5, theme: 'Ambition', quote: 'The cowards never started and the weak died along the way. That leaves us.' },
  { title: 'The Third Door', author: 'Alex Banayan', season: 'The Village', chapter: 5, theme: 'Access', quote: 'There\u2019s always a way in. You just have to be willing to look for it.' },
  { title: 'Outliers', author: 'Malcolm Gladwell', season: 'The Village', chapter: 5, theme: 'Success', quote: 'Practice isn\u2019t the thing you do once you\u2019re good. It\u2019s the thing you do that makes you good.' },
  // Season 2: The Road Out (Chapters 6-10)
  { title: 'Limitless', author: 'Jim Kwik', season: 'The Road Out', chapter: 6, theme: 'Learning', quote: 'If knowledge is power, learning is your superpower.' },
  { title: 'Leonardo da Vinci', author: 'Walter Isaacson', season: 'The Road Out', chapter: 6, theme: 'Curiosity', quote: 'The richness of his curiosity came from his willingness to be relentlessly diverted.' },
  { title: 'A Short History of Nearly Everything', author: 'Bill Bryson', season: 'The Road Out', chapter: 6, theme: 'Wonder', quote: 'To be alive at all involves some risk\u2014and an extraordinary stroke of luck.' },
  { title: 'How to Win Friends and Influence People', author: 'Dale Carnegie', season: 'The Road Out', chapter: 7, theme: 'Relationships', quote: 'You can make more friends in two months by becoming interested in other people than in two years by trying to get others interested in you.' },
  { title: 'Never Split the Difference', author: 'Chris Voss', season: 'The Road Out', chapter: 7, theme: 'Negotiation', quote: 'He who has learned to disagree without being disagreeable has discovered the most valuable secret of negotiation.' },
  { title: 'The Go-Giver', author: 'Bob Burg & John David Mann', season: 'The Road Out', chapter: 7, theme: 'Giving', quote: 'Your true worth is determined by how much more you give in value than you take in payment.' },
  { title: 'Influence', author: 'Robert Cialdini', season: 'The Road Out', chapter: 7, theme: 'Persuasion', quote: 'A well-known principle of human behavior says that when we ask someone to do us a favor we will be more successful if we provide a reason.' },
  { title: 'Leaders Eat Last', author: 'Simon Sinek', season: 'The Road Out', chapter: 7, theme: 'Trust', quote: 'Leadership is a choice. It is not a rank.' },
  { title: 'The Hard Thing About Hard Things', author: 'Ben Horowitz', season: 'The Road Out', chapter: 8, theme: 'Leadership', quote: 'The hard thing isn\u2019t setting a big, hairy, audacious goal. The hard thing is laying people off when you miss it.' },
  { title: 'Principles', author: 'Ray Dalio', season: 'The Road Out', chapter: 8, theme: 'Discipline', quote: 'Pain plus reflection equals progress.' },
  { title: 'Mindset', author: 'Carol Dweck', season: 'The Road Out', chapter: 8, theme: 'Growth', quote: 'Becoming is better than being.' },
  { title: 'Ego Is the Enemy', author: 'Ryan Holiday', season: 'The Road Out', chapter: 8, theme: 'Humility', quote: 'Wherever you are, whatever you\u2019re doing, your worst enemy already lives inside you: your ego.' },
  { title: 'Beyond Order', author: 'Jordan Peterson', season: 'The Road Out', chapter: 8, theme: 'Order', quote: 'Do not carelessly denigrate social institutions or creative achievement.' },
  { title: 'The Compound Effect', author: 'Darren Hardy', season: 'The Road Out', chapter: 9, theme: 'Consistency', quote: 'Small, smart choices + consistency + time = radical difference.' },
  { title: 'Factfulness', author: 'Hans Rosling', season: 'The Road Out', chapter: 9, theme: 'Clarity', quote: 'Forming your worldview by relying on the media would be like forming your view about me by looking only at a picture of my foot.' },
  { title: 'The Rational Optimist', author: 'Matt Ridley', season: 'The Road Out', chapter: 9, theme: 'Progress', quote: 'The cumulative accretion of knowledge by specialists is the great story of our species.' },
  { title: 'The Millionaire Fastlane', author: 'MJ DeMarco', season: 'The Road Out', chapter: 10, theme: 'Wealth', quote: 'The ride to wealth is paved on a road of process, not events.' },
  { title: 'The Lean Startup', author: 'Eric Ries', season: 'The Road Out', chapter: 10, theme: 'Iteration', quote: 'The only way to win is to learn faster than anyone else.' },
  { title: 'ReWork', author: 'Jason Fried & David Heinemeier Hansson', season: 'The Road Out', chapter: 10, theme: 'Building', quote: 'Planning is guessing.' },
  { title: 'Your Next Five Moves', author: 'Patrick Bet-David', season: 'The Road Out', chapter: 10, theme: 'Strategy', quote: 'The person with the most options usually wins.' },
  // Season 3: Love & Building (Chapters 11-15)
  { title: 'Quiet', author: 'Susan Cain', season: 'Love & Building', chapter: 11, theme: 'Introversion', quote: 'There\u2019s zero correlation between being the best talker and having the best ideas.' },
  { title: 'Attached', author: 'Amir Levine & Rachel Heller', season: 'Love & Building', chapter: 11, theme: 'Attachment', quote: 'When two people form a couple, they influence each other in profound ways from then on.' },
  { title: 'Nonviolent Communication', author: 'Marshall Rosenberg', season: 'Love & Building', chapter: 11, theme: 'Honesty', quote: 'What others do may be the stimulus of our feelings, but not the cause.' },
  { title: 'The Courage to Be Disliked', author: 'Ichiro Kishimi & Fumitake Koga', season: 'Love & Building', chapter: 11, theme: 'Freedom', quote: 'Freedom is being disliked by other people.' },
  { title: 'The Four Agreements', author: 'Don Miguel Ruiz', season: 'Love & Building', chapter: 12, theme: 'Wisdom', quote: 'Be impeccable with your word.' },
  { title: 'Tuesdays with Morrie', author: 'Mitch Albom', season: 'Love & Building', chapter: 12, theme: 'Love', quote: 'Death ends a life, not a relationship.' },
  { title: 'The Fault in Our Stars', author: 'John Green', season: 'Love & Building', chapter: 12, theme: 'Finitude', quote: 'You don\u2019t get to choose if you get hurt in this world, but you do have some say in who hurts you.' },
  { title: 'The Psychology of Money', author: 'Morgan Housel', season: 'Love & Building', chapter: 13, theme: 'Wealth', quote: 'Doing well with money has a little to do with how smart you are and a lot to do with how you behave.' },
  { title: 'Measure What Matters', author: 'John Doerr', season: 'Love & Building', chapter: 13, theme: 'Metrics', quote: 'Ideas are easy. Execution is everything.' },
  { title: 'The Everything Store', author: 'Brad Stone', season: 'Love & Building', chapter: 13, theme: 'Scale', quote: 'Your margin is my opportunity.' },
  { title: 'Hooked', author: 'Nir Eyal', season: 'Love & Building', chapter: 13, theme: 'Habit', quote: 'Habits are the brain\u2019s way of saving effort.' },
  { title: 'The Black Swan', author: 'Nassim Nicholas Taleb', season: 'Love & Building', chapter: 14, theme: 'Risk', quote: 'The inability to predict outliers implies the inability to predict the course of history.' },
  { title: 'Fooled by Randomness', author: 'Nassim Nicholas Taleb', season: 'Love & Building', chapter: 14, theme: 'Chance', quote: 'Mild success can be explainable by skills and labor. Wild success is attributable to variance.' },
  { title: 'Skin in the Game', author: 'Nassim Nicholas Taleb', season: 'Love & Building', chapter: 14, theme: 'Commitment', quote: 'Don\u2019t tell me what you think, tell me what you have in your portfolio.' },
  { title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', season: 'Love & Building', chapter: 14, theme: 'Decision', quote: 'Nothing in life is as important as you think it is, while you are thinking about it.' },
  { title: 'Beyond Good and Evil', author: 'Friedrich Nietzsche', season: 'Love & Building', chapter: 14, theme: 'Morality', quote: 'He who fights with monsters should look to it that he himself does not become a monster.' },
  { title: 'Reality Is Not What It Seems', author: 'Carlo Rovelli', season: 'Love & Building', chapter: 14, theme: 'Reality', quote: 'We are made of the same stardust of which all things are made.' },
  { title: 'Benjamin Franklin: An American Life', author: 'Walter Isaacson', season: 'Love & Building', chapter: 15, theme: 'Mentorship', quote: 'Energy and persistence conquer all things.' },
  { title: 'Einstein: His Life and Universe', author: 'Walter Isaacson', season: 'Love & Building', chapter: 15, theme: 'Genius', quote: 'Imagination is more important than knowledge.' },
  { title: 'Steve Jobs', author: 'Walter Isaacson', season: 'Love & Building', chapter: 15, theme: 'Vision', quote: 'The people who are crazy enough to think they can change the world are the ones who do.' },
  { title: 'The Story of Philosophy', author: 'Will Durant', season: 'Love & Building', chapter: 15, theme: 'Philosophy', quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' },
  // Season 4: Success & Breaking (Chapters 16-20)
  { title: 'The Subtle Art of Not Giving a F*ck', author: 'Mark Manson', season: 'Success & Breaking', chapter: 16, theme: 'Priorities', quote: 'Who you are is defined by what you\u2019re willing to struggle for.' },
  { title: 'Everything Is F*cked', author: 'Mark Manson', season: 'Success & Breaking', chapter: 16, theme: 'Hope', quote: 'Pain is the universal constant of life.' },
  { title: 'Digital Minimalism', author: 'Cal Newport', season: 'Success & Breaking', chapter: 16, theme: 'Attention', quote: 'Solitude is a subjective state in which your mind is free from input from other minds.' },
  { title: 'Indistractable', author: 'Nir Eyal', season: 'Success & Breaking', chapter: 16, theme: 'Focus', quote: 'You can\u2019t call something a distraction unless you know what it is distracting you from.' },
  { title: 'Meditations', author: 'Marcus Aurelius', season: 'Success & Breaking', chapter: 17, theme: 'Stoicism', quote: 'You have power over your mind\u2014not outside events. Realize this, and you will find strength.' },
  { title: 'Stillness Is the Key', author: 'Ryan Holiday', season: 'Success & Breaking', chapter: 17, theme: 'Stillness', quote: 'Stillness is what aims the archer\u2019s arrow.' },
  { title: 'The Daily Stoic', author: 'Ryan Holiday', season: 'Success & Breaking', chapter: 18, theme: 'Practice', quote: 'The chief task in life is simply this: to identify and separate matters so that I can say clearly which are externals not under my control.' },
  { title: 'Lives of the Stoics', author: 'Ryan Holiday', season: 'Success & Breaking', chapter: 18, theme: 'Stoicism', quote: 'A philosopher is not measured by what they say, but by what they do.' },
  { title: 'Letters from a Stoic', author: 'Seneca', season: 'Success & Breaking', chapter: 18, theme: 'Wisdom', quote: 'We suffer more often in imagination than in reality.' },
  { title: 'The Monk Who Sold His Ferrari', author: 'Robin Sharma', season: 'Success & Breaking', chapter: 18, theme: 'Balance', quote: 'The mind is a wonderful servant, but a terrible master.' },
  { title: 'Homo Deus', author: 'Yuval Noah Harari', season: 'Success & Breaking', chapter: 19, theme: 'Future', quote: 'In the twenty-first century, the new mantra will be: knowledge equals data.' },
  { title: '21 Lessons for the 21st Century', author: 'Yuval Noah Harari', season: 'Success & Breaking', chapter: 19, theme: 'Clarity', quote: 'In a world deluged by irrelevant information, clarity is power.' },
  { title: 'The Art of Thinking Clearly', author: 'Rolf Dobelli', season: 'Success & Breaking', chapter: 20, theme: 'Cognition', quote: 'It is much easier to recognize other people\u2019s mistakes than our own.' },
  { title: 'Grit', author: 'Angela Duckworth', season: 'Success & Breaking', chapter: 20, theme: 'Perseverance', quote: 'Enthusiasm is common. Endurance is rare.' },
  // Season 5: Wisdom & Legacy (Chapters 21-28)
  { title: 'The Innovator\u2019s Dilemma', author: 'Clayton Christensen', season: 'Wisdom & Legacy', chapter: 21, theme: 'Disruption', quote: 'Disruptive technology should be framed as a marketing challenge, not a technological one.' },
  { title: 'The Millionaire Next Door', author: 'Thomas Stanley & William Danko', season: 'Wisdom & Legacy', chapter: 22, theme: 'Wealth', quote: 'Wealth is more often the result of a lifestyle of hard work, perseverance, planning, and self-discipline.' },
  { title: 'I Will Teach You to Be Rich', author: 'Ramit Sethi', season: 'Wisdom & Legacy', chapter: 22, theme: 'Money', quote: 'Spend extravagantly on the things you love, and cut costs mercilessly on the things you don\u2019t.' },
  { title: 'Money: Master the Game', author: 'Tony Robbins', season: 'Wisdom & Legacy', chapter: 22, theme: 'Finance', quote: 'The secret to wealth is simple: Find a way to do more for others than anyone else does.' },
  { title: 'Drive', author: 'Daniel Pink', season: 'Wisdom & Legacy', chapter: 23, theme: 'Motivation', quote: 'Human beings have an innate inner drive to be autonomous, self-determined, and connected.' },
  { title: 'Flow', author: 'Mihaly Csikszentmihalyi', season: 'Wisdom & Legacy', chapter: 23, theme: 'Absorption', quote: 'The best moments in our lives are not the passive, receptive, relaxing times.' },
  { title: 'The Happiness Hypothesis', author: 'Jonathan Haidt', season: 'Wisdom & Legacy', chapter: 23, theme: 'Happiness', quote: 'Happiness comes from between. Between you and others, between you and your work.' },
  { title: 'Essentialism', author: 'Greg McKeown', season: 'Wisdom & Legacy', chapter: 23, theme: 'Less', quote: 'If you don\u2019t prioritize your life, someone else will.' },
  { title: 'The Art of War', author: 'Sun Tzu', season: 'Wisdom & Legacy', chapter: 24, theme: 'Strategy', quote: 'The supreme art of war is to subdue the enemy without fighting.' },
  { title: 'The 48 Laws of Power', author: 'Robert Greene', season: 'Wisdom & Legacy', chapter: 25, theme: 'Power', quote: 'Never outshine the master.' },
  { title: 'When Breath Becomes Air', author: 'Paul Kalanithi', season: 'Wisdom & Legacy', chapter: 26, theme: 'Meaning', quote: 'You can\u2019t ever reach perfection, but you can believe in an asymptote toward which you are ceaselessly striving.' },
  { title: 'Talk Like TED', author: 'Carmine Gallo', season: 'Wisdom & Legacy', chapter: 27, theme: 'Communication', quote: 'Ideas are the currency of the twenty-first century.' },
  { title: 'The Life You Can Save', author: 'Peter Singer', season: 'Wisdom & Legacy', chapter: 28, theme: 'Giving', quote: 'If it is in our power to prevent something bad from happening, without sacrificing anything of comparable moral importance, we ought to do it.' },
  { title: 'Give and Take', author: 'Adam Grant', season: 'Wisdom & Legacy', chapter: 28, theme: 'Generosity', quote: 'The true measure of a man is how he treats someone who can do him absolutely no good.' },
  { title: 'The Second Mountain', author: 'David Brooks', season: 'Wisdom & Legacy', chapter: 28, theme: 'Purpose', quote: 'The first mountain is about building up the ego. The second mountain is about shedding it.' },
  // Season 6: The Inheritance (Chapters 29-40)
  { title: 'Die with Zero', author: 'Bill Perkins', season: 'The Inheritance', chapter: 29, theme: 'Legacy', quote: 'The business of life is the acquisition of memories.' },
  { title: 'A Calendar of Wisdom', author: 'Leo Tolstoy', season: 'The Inheritance', chapter: 31, theme: 'Wisdom', quote: 'The most important time is now, the most important person is the one you are with.' },
  { title: 'The Lessons of History', author: 'Will & Ariel Durant', season: 'The Inheritance', chapter: 31, theme: 'History', quote: 'History is, above all else, the creation and recording of that heritage.' },
  { title: 'The Power of Your Subconscious Mind', author: 'Joseph Murphy', season: 'The Inheritance', chapter: 32, theme: 'Mind', quote: 'Change your thoughts, and you change your destiny.' },
  { title: 'Autobiography of a Yogi', author: 'Paramahansa Yogananda', season: 'The Inheritance', chapter: 32, theme: 'Stillness', quote: 'Self-realization is the knowing\u2014in body, mind, and soul\u2014that we are one with the omnipresence of God.' },
  { title: 'War and Peace', author: 'Leo Tolstoy', season: 'The Inheritance', chapter: 36, theme: 'Time', quote: 'The two most powerful warriors are patience and time.' },
  { title: 'The Dip', author: 'Seth Godin', season: 'The Inheritance', chapter: 37, theme: 'Quitting', quote: 'Winners quit all the time. They just quit the right stuff at the right time.' },
  { title: 'Daring Greatly', author: 'Bren\u00e9 Brown', season: 'The Inheritance', chapter: 38, theme: 'Courage', quote: 'Vulnerability is not winning or losing; it\u2019s having the courage to show up when you can\u2019t control the outcome.' },
];
